feature/aggregator unification
rhayes777/PyAutoFit pull request #872
Opened 2023-11-10 15:43 UTC by rhayes777

More methods to make align the interfaces of the directory and database aggregators

2023-11-13 18:48 UTC, Jammy2211 approved these changes

2023-11-13 18:49 UTC, Jammy2211 requested changes
This PR breaks unit tests on PyAutoGalaxy (and other projects):

```
../PyAutoConf/autoconf/conf.py:364: in wrapper
    result = func(*args, **kwargs)
test_autogalaxy/aggregator/conftest.py:52: in aggregator_from
    agg.add_directory(directory=result_path)
../PyAutoFit/autofit/database/aggregator/aggregator.py:419: in add_directory
    scraper.scrape()
../PyAutoFit/autofit/database/aggregator/scrape.py:48: in scrape
    for fit in self._fits():
../PyAutoFit/autofit/database/aggregator/scrape.py:84: in _fits
    info=item.info,
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <PhaseOutput name=
non_linear_search=mocksearch
            >, name = 'info'

    def __getattr__(self, name):
        """
        Attempt to load a pickle by the same name from the search output directory.

        dataset.pickle, meta_dataset.pickle etc.
        """
        result = self.value(name)

        if result is not None:
            return result

>       raise AttributeError(f"No attribute named {name}")
E       AttributeError: No attribute named info

../PyAutoFit/autofit/aggregator/search_output.py:130: AttributeError
```

2023-11-17 07:53 UTC, rhayes777 commented
Fixed. Autogalaxy tests are still failing but I think it's unrelated.

```python-traceback
A = array([[ 0.46131443,  0.22420495, -0.14681808, -0.16924766,  0.06199813,
         0.12331874],
       [ 0.22420495,  0...,
         0.22420495],
       [ 0.12331874,  0.06199813, -0.16924766, -0.14681808,  0.22420495,
         0.46131443]])

    def mat_inv(A):
    #     I = numpy.eye(A.shape[0], A.shape[1])
>       B = scipy.linalg.pinv2(A)
E       AttributeError: module 'scipy.linalg' has no attribute 'pinv2'

2023-11-17 08:59 UTC, Jammy2211 approved these changes

2023-11-17 08:59 UTC, merged